# Generated by Django 3.2.3 on 2024-12-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='short_link',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
